# permissions to do viewer freeipaissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freeipaissuer-viewer-role
rules:
- apiGroups:
  - freeipa.org.freeipa.org
  resources:
  - freeipaissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freeipa.org.freeipa.org
  resources:
  - freeipaissuers/status
  verbs:
  - get
