# permissions to do edit freeipaissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freeipaissuer-editor-role
rules:
- apiGroups:
  - freeipa.org.freeipa.org
  resources:
  - freeipaissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freeipa.org.freeipa.org
  resources:
  - freeipaissuers/status
  verbs:
  - get
  - patch
  - update
