
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
