// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIpaAuthSpec) DeepCopyInto(out *FreeIpaAuthSpec) {
	*out = *in
	in.UserPass.DeepCopyInto(&out.UserPass)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIpaAuthSpec.
func (in *FreeIpaAuthSpec) DeepCopy() *FreeIpaAuthSpec {
	if in == nil {
		return nil
	}
	out := new(FreeIpaAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIpaIssuer) DeepCopyInto(out *FreeIpaIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIpaIssuer.
func (in *FreeIpaIssuer) DeepCopy() *FreeIpaIssuer {
	if in == nil {
		return nil
	}
	out := new(FreeIpaIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FreeIpaIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIpaIssuerList) DeepCopyInto(out *FreeIpaIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FreeIpaIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIpaIssuerList.
func (in *FreeIpaIssuerList) DeepCopy() *FreeIpaIssuerList {
	if in == nil {
		return nil
	}
	out := new(FreeIpaIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FreeIpaIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIpaIssuerSpec) DeepCopyInto(out *FreeIpaIssuerSpec) {
	*out = *in
	if in.CABundle != nil {
		in, out := &in.CABundle, &out.CABundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIpaIssuerSpec.
func (in *FreeIpaIssuerSpec) DeepCopy() *FreeIpaIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(FreeIpaIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIpaIssuerStatus) DeepCopyInto(out *FreeIpaIssuerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIpaIssuerStatus.
func (in *FreeIpaIssuerStatus) DeepCopy() *FreeIpaIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(FreeIpaIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIpaUserPassAuthSpec) DeepCopyInto(out *FreeIpaUserPassAuthSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIpaUserPassAuthSpec.
func (in *FreeIpaUserPassAuthSpec) DeepCopy() *FreeIpaUserPassAuthSpec {
	if in == nil {
		return nil
	}
	out := new(FreeIpaUserPassAuthSpec)
	in.DeepCopyInto(out)
	return out
}
